name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dart
      uses: subosito/flutter-action@v2
    - name: Get Dependencies
      run: dart pub get
    - name: Run Tests
      run: dart test
    - name: Measure Coverage
      run: flutter test --coverage
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        file: coverage/lcov.info
