name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dart
      uses: dart-lang/setup-dart@v1
    - name: Get Dependencies
      run: dart pub get
    - name: Run Tests
      run: dart run test
    - name: Measure Coverage
      run: pub run test_coverage
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        file: coverage/lcov.info
